# Generated by Django 5.1.6 on 2025-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='expire_ad',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
