# Generated by Django 5.2.1 on 2025-05-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.EmailField(max_length=254),
        ),
    ]
