# Generated by Django 5.1.6 on 2025-08-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_emaillog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='error',
            new_name='error_message',
        ),
    ]
