# Generated by Django 5.2.1 on 2025-05-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_alter_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
    ]
